package entity.xml;
// Generated Feb 21, 2017 1:01:49 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Departs generated by hbm2java
 */
public class Departs  implements java.io.Serializable {


     private String id;
     private String name;
     private Set<Staffs> staffses = new HashSet<Staffs>(0);

    public Departs() {
    }

	
    public Departs(String id, String name) {
        this.id = id;
        this.name = name;
    }
    public Departs(String id, String name, Set<Staffs> staffses) {
       this.id = id;
       this.name = name;
       this.staffses = staffses;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<Staffs> getStaffses() {
        return this.staffses;
    }
    
    public void setStaffses(Set<Staffs> staffses) {
        this.staffses = staffses;
    }




}


