package entity.xml;
// Generated Feb 21, 2017 1:01:49 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * Records generated by hbm2java
 */
public class Records  implements java.io.Serializable {


     private long id;
     private Staffs staffs;
     private int type;
     private String reason;
     private Serializable date;

    public Records() {
    }

    public Records(long id, Staffs staffs, int type, String reason, Serializable date) {
       this.id = id;
       this.staffs = staffs;
       this.type = type;
       this.reason = reason;
       this.date = date;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Staffs getStaffs() {
        return this.staffs;
    }
    
    public void setStaffs(Staffs staffs) {
        this.staffs = staffs;
    }
    public int getType() {
        return this.type;
    }
    
    public void setType(int type) {
        this.type = type;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }
    public Serializable getDate() {
        return this.date;
    }
    
    public void setDate(Serializable date) {
        this.date = date;
    }




}


